package hibernate;


import java.math.BigDecimal;

/**
 * CustomerEntity generated by hbm2java
 */
public class CustomerEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7223906314923409260L;
	private long customerId;
	private String customerName;
	private String companyName;
	private BigDecimal balance;
	private String address;
	private String phone;
	private String fax;
	private String email;
	private boolean active;
	private long createdOn;
	private long updatedOn;
	private String remarks;

	public CustomerEntity() {
	}

	public CustomerEntity(String customerName, String companyName,
			BigDecimal balance, String address, String phone, String fax,
			String email, boolean active, long createdOn, long updatedOn, String remarks) {
		this.customerName = customerName;
		this.companyName = companyName;
		this.balance = balance;
		this.address = address;
		this.phone = phone;
		this.fax = fax;
		this.email = email;
		this.active = active;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.remarks = remarks;
	}

	public long getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(long customerId) {
		this.customerId = customerId;
	}

	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	public BigDecimal getBalance() {
		return this.balance;
	}

	public void setBalance(BigDecimal balance) {
		this.balance = balance;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public long getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public long getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(long updatedOn) {
		this.updatedOn = updatedOn;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public boolean isActive() {
		return active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}
}
