package hibernate;
/**
 * CustomerEntity generated by hbm2java
 */
public class UserEntity implements java.io.Serializable {

	private static final long serialVersionUID = 991395353754108875L;
	private long userId;
	private String userName;
	private Integer type;
	private long createdOn;

	public UserEntity() {
	}
	
	public UserEntity(String userName, long createdOn, Integer type) {
		this.userName = userName;
		this.createdOn = createdOn;
		this.type = type;
	}

	public long getUserId() {
		return userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public long getCreatedOn() {
		return createdOn;
	}

	public void setCreatedOn(long createdOn) {
		this.createdOn = createdOn;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}


}
